name: Release

on:
  release:
    types: [created]

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn install --immutable
      - run: yarn build:all

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --immutable
      - run: yarn build:all
      - run: yarn publish:all --dry-run
      - run: yarn publish:all --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install --immutable
      - run: yarn build:all
      - run: yarn docs:generate-client
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: site
